#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source bash_proile for env
if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile;
fi

# Set up plugins
plugins=(git history brew gitfast pip)

# Command completion for conda
fpath+=~/git_repos/conda-zsh-completion
compinit conda

# Command completion for gcloud
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

# Set CLOUDSDK_PYTHON because our system python is python3
export CLOUDSDK_PYTHON=$(which python2)

export EDITOR='subl -nw'
export VISUAL="$EDITOR"


# Kubernetes command line completions
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh);
fi

alias subla='\subl -a'
alias subl='\subl -n'

function add_conda_path {
  export PATH="/Users/jianliu/anaconda3/bin:$PATH"
}

export KEYTIMEOUT=1

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
. "/Users/jianliu/.acme.sh/acme.sh.env"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env" ] && source "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env"
[ -f "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env" ] && source "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env"

THIS_FILE="${(%):-%N}"

_search_alias() {
  alias | grep "$1"
}

_new_alias() {
    echo "alias $1=\"${@:2}\"" >> "$THIS_FILE";
    source "$THIS_FILE"
    alias "$1"
}
alias sa=_search_alias
alias new-alias=_new_alias
alias subl="subl -n"
alias g="git"
alias subla="subl -a"
alias subla="\subl -a"
